[project]
name = "nerf"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "imageio>=2.37.2",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
